### ISSUE TITLE
Problem in Parameter file (params.in) of demo

### ISSUE THREAD

**Issue by SuwenJunliu** [akuhara/RF_INV#1]
When I installed the package and ran the program with the file "params.in" in demo, I receive:

> ERROR: cannot create Note:/params.in.copy

I think the reason why it happened is that : There is a mistake in params.in

```
# Output directory
#---------------------------------------------------------
# OUTDIR: output directory 
          Note: quotation mark is necessary
'./result'
#
```
There should be a # before "Note: quotation mark is necessary"

When I add the # before the "Note: quotation mark is necessary",  I receive:

>  Sigma is solved for trace           1
> At line 240 of file src/params.f90
> Fortran runtime error: Bad real number in item 2 of list input

Then I check the fortran code of "params.f90", I found that "line 240" is the parameter of sigma.
According to the demo of params.in, there should be 3 line about "Min./Max. of noise sigma". In order words, This part of "params.in" 

```
# Min./Max. of noise sigma
0.005 0.08
#
```

should be changed into

```
# Min./Max. of noise sigma
0.005 0.08
0.005 0.08
0.005 0.08
#
```
Besides, before running this demo, we should prepare the SAC files and "reference.mod" file.

In the view of above, I think that if there is a specific demo, this program will be used easier.

**Comment by akuhara** [comment]
I really appreciate your comments.
I will prepare for the demo shortly as you suggested.

**Comment by akuhara** [comment]
I have uploaded a directory for a synthetic case (sample_syn).
